#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/chef',
   :ref => 'master'

cookbook 'librarian',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/librarian',
   :ref => 'master'
  
cookbook 'system',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/system',
   :ref => 'master'

cookbook 'resolver',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/resolver',
   :ref => 'master'

cookbook 'cron',
  :git => 'https://github.com/opscode-cookbooks/cron',
  :ref => 'master'

cookbook 'ntp',
  :git => 'https://github.com/opscode-cookbooks/ntp',
  :ref => 'master'
   
cookbook 'sudo',
  :git => 'https://github.com/opscode-cookbooks/sudo',
  :ref => 'master'