#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/chef',
   :ref => 'master'

cookbook 'librarian',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/librarian',
   :ref => 'master'
  
cookbook 'git',
   :git => 'https://github.com/opscode-cookbooks/git',
   :ref => 'master'